name: Multi-container deployment
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t w0itke/multi-client-tests ./client
      - run: docker run -e CI=true w0itke/react-test npm run test
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t w0itke/multi-client ./client
      - run: docker push w0itke/multi-client
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t w0itke/multi-nginx ./nginx
      - run: docker push w0itke/multi-nginx
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t w0itke/multi-server ./server
      - run: docker push w0itke/multi-server
  build-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t w0itke/multi-worker ./worker
      - run: docker push w0itke/multi-worker


